name: 'Continuous Integration'
on:
  push:
    branches-ignore:
      - 'production'
    tags-ignore:
      - '*'
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/ci.yml'
      - '.travis.yml'
      - '.gitignore'
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths:
      - '**'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Build Site
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll b

      - name: Test Site
        run: |
          bash tools/test.sh
